spring.application.name=Replications

app.datasource.master.jdbc-url=jdbc:mysql://localhost:3306/test
app.datasource.master.username=root
app.datasource.master.password=*****
app.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver

app.datasource.replica.jdbc-url=jdbc:mysql://localhost:3307/replications
app.datasource.replica.username=root
app.datasource.replica.password=*****
app.datasource.replica.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.boot.context.config=DEBUG
